#!/bin/bash

set -e

if [ -n "$1" ]; then
	source "$1"
fi

echo "Installing database ${TOKYO_C_DATABASE_NAME}...  "

mysql --user="${TOKYO_C_DATABASE_USER}" --host="${TOKYO_C_DATABASE_HOST}" --password="${TOKYO_C_DATABASE_PASSWORD}" <<EOS
CREATE DATABASE ${TOKYO_C_DATABASE_NAME};
USE ${TOKYO_C_DATABASE_NAME};

CREATE TABLE friendships (
	person_0 VARCHAR(256),
	person_1 VARCHAR(256),
	created_at DATETIME,
	UNIQUE(person_0, person_1),
	INDEX(created_at)
);

CREATE TABLE messages (
        id INT PRIMARY KEY AUTO_INCREMENT,
        channel INT,
        author VARCHAR(256),
        is_event BOOLEAN,
        posted_at DATETIME,
        content VARCHAR(4096),
        INDEX(channel)
);

CREATE TABLE channels (
        id INT PRIMARY KEY AUTO_INCREMENT,
        name VARCHAR(256)
);

CREATE TABLE memberships (
        person VARCHAR(256),
        channel INT,
        UNIQUE(person, channel)
);
EOS

echo "Complete!"
