#!/bin/bash

source .env

echo "Installing database ${TOKYO_C_DATABASE_NAME}...  "

mysql --user="${TOKYO_C_DATABASE_USER}" --host="${TOKYO_C_DATABASE_HOST}" --password="${TOKYO_C_DATABASE_PASSWORD}" <<EOS
CREATE DATABASE ${TOKYO_C_DATABASE_NAME};
USE ${TOKYO_C_DATABASE_NAME};

CREATE TABLE friendships (
	person_0 INT,
	person_1 INT,
	UNIQUE(person_0, person_1)
);

CREATE TABLE messages (
        id INT PRIMARY KEY AUTO_INCREMENT,
        channel INT,
        author INT,
        is_event BOOLEAN,
        posted_at DATETIME,
        content VARCHAR(4096),
        INDEX(channel)
);

CREATE TABLE channels (
        id INT PRIMARY KEY AUTO_INCREMENT,
        name VARCHAR(256)
);

CREATE TABLE participations (
        person INT,
        channel INT,
        UNIQUE(person, channel)
);

CREATE TABLE people (
        id INT PRIMARY KEY AUTO_INCREMENT,
        name VARCHAR(128),
        token VARCHAR(1024)
);
EOS

echo "Complete!"
